name: remove old lokalise
inputs:
  token:
    description: 'GitHub auth token'
    default: ${{ github.token }}
on: pull_request
jobs:
  remove-old-lokalise:
    runs-on: ubuntu-latest
    if: startsWith(github.head_ref, 'lokalise-') == true
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '10'
      - name: remove old lokalise entries
        run: node remove-old-lokalise-prs.js
