name: remove old lokalise
on: pull_request
jobs:
  remove-old-lokalise:
    runs-on: ubuntu-latest
    if: startsWith(github.head_ref, 'lokalise-') == true
    steps:
      - uses: actions/setup-node@v2
      - uses: ./ 
        with:
          node-version: '10'
      - name: remove old lokalise entries
        run: npm start
